### ISSUE TITLE
Database Change means that Archive has not been archiving anything

### ISSUE THREAD

**Issue by ghost** [open-contracting/kingfisher-archive#11]
A while ago we changed the database structure on Kingfisher

https://github.com/open-contracting/kingfisher-process/commit/0c6d0531cc5307b1d165bc8dc411f6274fea766f#diff-84d496d7ab3f310d1b590d371592dc0c

This has broken Archive, and it hasn't tried to archive anything since then.

We do 

    select source_id, to_char(data_version, 'YYYYMMDD_HH24MISS') from collection where store_end_at is not null and transform_type is null

Need to change to 

    transform_type = ''

As well as doing this change, whoever does this should take the opportunity to make sure the `store_end_at` check is still correct to.

**Comment by jpmckinney** [comment]
Fixed yesterday: https://github.com/open-contracting/kingfisher-archive/commit/5d23fcd807d1ce200c1fb680368bcac9179318d7
