### ISSUE TITLE
Should we archive files people have local loaded?

### ISSUE THREAD

**Issue by ghost** [open-contracting/kingfisher-archive#14]
Currently we only archive files that were downloaded by Scrapy/Collect.

**Comment by ghost** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Archive to S3 and decommission server](https://trello.com/c/LSzAt3nw/234-archive-to-s3-and-decommission-server)

**Comment by jpmckinney** [comment]
See latest update in https://crm.open-contracting.org/issues/5533

Once that’s done, it’s just adding one folder to the archive script.
