### ISSUE TITLE
StrictHostKeyChecking=no should be removed

### ISSUE THREAD

**Issue by ghost** [open-contracting/kingfisher-archive#6]
This was just to get around a chicken/egg situation with Salt development (quote from others). Keys and auth_keys really should be managed by salt.

**Comment by jpmckinney** [comment]
Moved to https://github.com/open-contracting/deploy/issues/20 where it's more likely to be done along with other deployment issues.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Consider S3 Glacier instead of kingfisher-archive server](https://trello.com/c/xGkc11Pf/91-consider-s3-glacier-instead-of-kingfisher-archive-server)
